<?php

namespace Database\Seeders;
use App\Models\Actividad;
use Illuminate\Database\Seeder;

class ActividadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            Actividad::create(['descripcion'=>'PISO DE LADRILLO DE CEMENTO GRIS 25X25 CMS.','unidad'=>'M2','porcentaje'=>'0','costo'=>'95.69']);
            Actividad::create(['descripcion'=>'REPELLO DE PARED','unidad'=>'M2','porcentaje'=>'0','costo'=>'27.82']);
            Actividad::create(['descripcion'=>'BOTAGUAS LAMINA GALVANIZADA 0.455 M DE ANCHO','unidad'=>'ML','porcentaje'=>'0','costo'=>'91.39']);
            Actividad::create(['descripcion'=>'AFINADO DE CUADRADOS MORTERO 1:1','unidad'=>'ML','porcentaje'=>'0','costo'=>'5.37']);
            Actividad::create(['descripcion'=>'REPELLO DE CUADRADOS 0.20 MTS. DE ANCHO','unidad'=>'ML','porcentaje'=>'0','costo'=>'14.6']);
            Actividad::create(['descripcion'=>'PINTURA PARA ESTRUCTURA METALICA','unidad'=>'ML','porcentaje'=>'0','costo'=>'2.7']);
            Actividad::create(['descripcion'=>'EXCAVACION A MANO HASTA 1.50 M ( MATERIAL BLANDO )','unidad'=>'M3','porcentaje'=>'0','costo'=>'32.1']);
            Actividad::create(['descripcion'=>'AFINADO DE SUPERFICIES VERTICALES 1:1','unidad'=>'M2','porcentaje'=>'0','costo'=>'11.19']);
            Actividad::create(['descripcion'=>'CANAL DE A. LL. ANCHO=25 CMS; H=20 CMS; LAM. GAL #26','unidad'=>'ML','porcentaje'=>'0','costo'=>'125.9']);
            Actividad::create(['descripcion'=>'CANAL A. LL. ANCHO=25 CMS; H=20 CMS. LAM GALV #24','unidad'=>'ML','porcentaje'=>'0','costo'=>'78.7']);
            Actividad::create(['descripcion'=>'CUBIERTA DE LAMINA DURALUM','unidad'=>'M2','porcentaje'=>'0','costo'=>'22.76']);
            Actividad::create(['descripcion'=>'CONCRETEADO 1:2:2.5 E=5 CMS. Ø 1/4" A 25 CMS. A.S.','unidad'=>'M2','porcentaje'=>'0','costo'=>'62.68']);
            Actividad::create(['descripcion'=>'CONCRETO ARMADO PARA COLUMNA ( 4 # 6 )','unidad'=>'M3','porcentaje'=>'0','costo'=>'834.24']);
            Actividad::create(['descripcion'=>'DEMOLICION DE PAVIMENTO ( CONCRETO HIDRAULICO )','unidad'=>'M2','porcentaje'=>'0','costo'=>'12.14']);
            Actividad::create(['descripcion'=>'DESTRONCONADO ARBOL H= 5-6 MTS, TALLO=20 CMS.','unidad'=>'C/U','porcentaje'=>'0','costo'=>'43.08']);
            Actividad::create(['descripcion'=>'DEMOLICION DE REPELLO','unidad'=>'M2','porcentaje'=>'0','costo'=>'3.4']);
            Actividad::create(['descripcion'=>'DEMOLICION DE PISO','unidad'=>'M2','porcentaje'=>'0','costo'=>'4.24']);
            Actividad::create(['descripcion'=>'PINTURA DE ACEITE','unidad'=>'M2','porcentaje'=>'0','costo'=>'9.38']);
            Actividad::create(['descripcion'=>'PINTURA EN CUADRADOS ( LATEX )','unidad'=>'ML','porcentaje'=>'0','costo'=>'1.73']);
            Actividad::create(['descripcion'=>'PINTURA DE AGUA ( LATEX )','unidad'=>'M2','porcentaje'=>'0','costo'=>'8.53']);
            Actividad::create(['descripcion'=>'LUMINARIA FLUORESCENTE DE 2X40 WATTS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'127.14']);
            Actividad::create(['descripcion'=>'LUMINARIA INCANDESCENTE DE 60 WATTS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'120.18']);
            Actividad::create(['descripcion'=>'PUERTA METALICA BOBLE HOJA, DOBLE FORRO','unidad'=>'C/U','porcentaje'=>'0','costo'=>'4285.92']);
            Actividad::create(['descripcion'=>'PISOS ZOCALO DE CEMENTO GRIS 25X7.5 CMS.','unidad'=>'ML','porcentaje'=>'0','costo'=>'19.53']);
            Actividad::create(['descripcion'=>'PARED DE BLOQUE DE CONCRETO 15X20X40 BASTONES 3/8" A 60 CMS.','unidad'=>'M2','porcentaje'=>'0','costo'=>'71.74']);
            Actividad::create(['descripcion'=>'PARED DE LADRILLO DE BARRO P/LAZO 1ER BLOCK','unidad'=>'M2','porcentaje'=>'0','costo'=>'81.72']);
            Actividad::create(['descripcion'=>'ROTULO','unidad'=>'C/U','porcentaje'=>'0','costo'=>'336.18']);
            Actividad::create(['descripcion'=>'RELLENO COMPACTADO CON TIERRA BLANCA  H=1.50 A 3.00 MTS','unidad'=>'M3','porcentaje'=>'0','costo'=>'170.45']);
            Actividad::create(['descripcion'=>'RELLENO COMPACTADO CON MATERIAL EXISTENTE','unidad'=>'M3','porcentaje'=>'0','costo'=>'57.03']);
            Actividad::create(['descripcion'=>'SOLERA DE FUNDACION ( 30X25 ) 4 Ø3/8" + 1 Ø1/4" A.C. 10 CMS 1:2:2','unidad'=>'ML','porcentaje'=>'0','costo'=>'33.15']);
            Actividad::create(['descripcion'=>'SOLERA DE FUNDACION ( 25X20 ) 4Ø3/8" + 1Ø1/4" A.C. 15 CMS 1:2:2','unidad'=>'ML','porcentaje'=>'0','costo'=>'22.53']);
            Actividad::create(['descripcion'=>'TUBERIA Ø 4" PVC JR 160 PSI','unidad'=>'ML','porcentaje'=>'0','costo'=>'4.55']);
            Actividad::create(['descripcion'=>'TUBERIA Ø1/2" PVC 315 PSI','unidad'=>'ML','porcentaje'=>'0','costo'=>'15.13']);
            Actividad::create(['descripcion'=>'ZAPATA 1.5X1.5X0.25  1/2" A 24 CMS A.S. 1:2:2','unidad'=>'C/U','porcentaje'=>'0','costo'=>'212.43']);
            Actividad::create(['descripcion'=>'LIMPIEZA DE CANALETAS Y CHAPEO','unidad'=>'M2','porcentaje'=>'0','costo'=>'2.61']);
            Actividad::create(['descripcion'=>'DEMOLICION DE PISOS,ACERAS Y CANALETAS','unidad'=>'M2','porcentaje'=>'0','costo'=>'19.02']);
            Actividad::create(['descripcion'=>'DEMOLICION DE MARQUESINAS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'223.28']);
            Actividad::create(['descripcion'=>'DESALOJO','unidad'=>'M3','porcentaje'=>'0','costo'=>'114.51']);
            Actividad::create(['descripcion'=>'SOLERA DE FUNDACION 40X25 CMS 6#4,EST #2 A 15 CMS','unidad'=>'ML','porcentaje'=>'0','costo'=>'115.75']);
            Actividad::create(['descripcion'=>'SOLERA DE FUNDACION 30X20 CMS. 4#3, EST #2 A 15 CMS.','unidad'=>'ML','porcentaje'=>'0','costo'=>'69.67']);
            Actividad::create(['descripcion'=>'CARGADERO 15 X 15 CMS 4#3 EST #2 A 15 CMS','unidad'=>'ML','porcentaje'=>'0','costo'=>'72.94']);
            Actividad::create(['descripcion'=>'NERVIO 15X15 CMS 4#3 EST #2 A 15 CMS','unidad'=>'ML','porcentaje'=>'0','costo'=>'76.45']);
            Actividad::create(['descripcion'=>'MURO DE MAMPOSTERIA','unidad'=>'M3','porcentaje'=>'0','costo'=>'416.71']);
            Actividad::create(['descripcion'=>'REPELLO Y AFINADO DE CUADRADOS EN PUERTAS Y VENTANAS','unidad'=>'ML','porcentaje'=>'0','costo'=>'38.65']);
            Actividad::create(['descripcion'=>'CEPO UNION PARED Y LAMINA DE TECHO ( REPELLADO Y AFINADO EN AMBAS CARAS )','unidad'=>'ML','porcentaje'=>'0','costo'=>'20.96']);
            Actividad::create(['descripcion'=>'RESANE DE GRIETAS EN PAREDES','unidad'=>'S.G.','porcentaje'=>'0','costo'=>'374.31']);
            Actividad::create(['descripcion'=>'RESANE DE CANALETA','unidad'=>'ML','porcentaje'=>'0','costo'=>'22.89']);
            Actividad::create(['descripcion'=>'GRADA DE LADRILLO DE CALAVERA EN TERMINACION DE PISO','unidad'=>'ML','porcentaje'=>'0','costo'=>'10.63']);
            Actividad::create(['descripcion'=>'PLETINA 2 X 1/8 DE 40 CMS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'22.74']);
            Actividad::create(['descripcion'=>'MOJINETE DE LAMINA METALICA TIPO DURALUM CALIBRE 24','unidad'=>'M2','porcentaje'=>'0','costo'=>'143.99']);
            Actividad::create(['descripcion'=>'CIELO FALSO LOSETA DE FIBROCEMENTO Y ESTRUCTURA DE DE ALUMINIO TIPO PESADO','unidad'=>'M2','porcentaje'=>'0','costo'=>'61.63']);
            Actividad::create(['descripcion'=>'BAJADA DE AGUAS LLUVIAS PVC Ø 3" 80 PSI','unidad'=>'ML','porcentaje'=>'0','costo'=>'76.56']);
            Actividad::create(['descripcion'=>'PUERTA UNA HOJA 1"X1"X1/8" LAMINA DE HIERRO E=1/16" AMBAS CARAS ( INCLUYE CHAPA YALE, BISAGRA TIPO CAPSULA, PASADORES, PINTURA Y CONTRAMARCO )','unidad'=>'M2','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'DEFENSA METALICA DE BARRA SOLIDA CUADRADA 1/2"','unidad'=>'M2','porcentaje'=>'0','costo'=>'127.46']);
            Actividad::create(['descripcion'=>'PUERTA DE MADERA PLYWOOD, ESTRUCTURA Y MOCHETA DE CEDRO CHAPA DE POMO , ENTINTADA Y BARNIZADA 0.90X2.10 MTS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'973.86']);
            Actividad::create(['descripcion'=>'VENTANA CELOSIA DE VIDRIO Y MARCO ALUMINIO ESTANDAR OP. DE CADENA','unidad'=>'M2','porcentaje'=>'0','costo'=>'385.2']);
            Actividad::create(['descripcion'=>'VENTANA DE CELOSIA DE VIDRIO Y MARCO ALUMINIO ESTANDAR OP. DE MARIPOSA','unidad'=>'M2','porcentaje'=>'0','costo'=>'321']);
            Actividad::create(['descripcion'=>'CEDAZO EN PUERTAS METALICAS','unidad'=>'M2','porcentaje'=>'0','costo'=>'53.5']);
            Actividad::create(['descripcion'=>'TUBERIA PVC  A.N. Ø6" 100PSI','unidad'=>'ML','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'CAJA DE CONEXIÓN 30X30 CMS. A.N.','unidad'=>'C/U','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'VALVULA GLOBO A.P. DE BRONCE Ø1/2" ( INCLUYE CAJA DE PROTECCION  )','unidad'=>'C/U','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'SANITARIO COMPLETO T/ ECONOMICO INCESA ST','unidad'=>'C/U','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'ESPEJO 40X60 CMS. E=5 MM','unidad'=>'C/U','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'ROTURA Y RESANADO DE POZO A.N. EXISTENTE','unidad'=>'C/U','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'TABLERO GENERAL TRIFASICO 120/240 V DE 24 ESPACIOS ( INCLUYE RED )','unidad'=>'ML','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'TOMACORRIENTE TRIFILIAR TIPO INDUSTRIAL','unidad'=>'C/U','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'DESPINTADO DE PAREDES DE LADRILLO DE CALAVERA ( CALEADAS )','unidad'=>'M2','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'PISO DE LADRILLO DE CEMENTO GRIS 30X30 CMS','unidad'=>'M2','porcentaje'=>'0','costo'=>'102.02']);
            Actividad::create(['descripcion'=>'PINTURA ANTICORROSIVA EN POLINES METALICOS EXISTENTES','unidad'=>'ML','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'PINTURA ANTICORROSIVA EN VIGAS METALICAS EXISTENTES ( INCLUYE ATIEZADORES )','unidad'=>'ML','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'PINTURA ANTICORROSIVA EN MOJINETES METALICOS EXISTENTES','unidad'=>'ML','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'COLUMNA DE 25X50 CMS. 6#4 EST. #2 A 15 CMS.','unidad'=>'ML','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'CARGADERO 25X50 CMS. 6#4 EST. #2 A 15 CMS.','unidad'=>'ML','porcentaje'=>'0','costo'=>'0']);
            Actividad::create(['descripcion'=>'TUBERIA PVC AN Ø4" 125 PSI','unidad'=>'ML','porcentaje'=>'0','costo'=>'41.49']);
            Actividad::create(['descripcion'=>'NERVIO N-1','unidad'=>'M3','porcentaje'=>'0','costo'=>'2464.38']);
            Actividad::create(['descripcion'=>'EXCAVACION','unidad'=>'M3','porcentaje'=>'0','costo'=>'39.32']);
            Actividad::create(['descripcion'=>'EXCAVACIÓN ZAPATA CORRIDA Z M-3','unidad'=>'M3','porcentaje'=>'0','costo'=>'51.36']);
            Actividad::create(['descripcion'=>'RELLENO COMPACTADO CON MATERIAL SELECTO','unidad'=>'M3','porcentaje'=>'0','costo'=>'55.64']);
            Actividad::create(['descripcion'=>'COMPACTACION CON SUELO CEMENTO PARA PISOS','unidad'=>'M3','porcentaje'=>'0','costo'=>'151.03']);
            Actividad::create(['descripcion'=>'EXCAVACIÓN PARA MURO M-1','unidad'=>'M3','porcentaje'=>'0','costo'=>'82.11']);
            Actividad::create(['descripcion'=>'NERVIO N','unidad'=>'M3','porcentaje'=>'0','costo'=>'3107.23']);
            Actividad::create(['descripcion'=>'ZAPATA Z-1','unidad'=>'M3','porcentaje'=>'0','costo'=>'1216.3']);
            Actividad::create(['descripcion'=>'COLUMNA C-1','unidad'=>'M3','porcentaje'=>'0','costo'=>'3107.56']);
            Actividad::create(['descripcion'=>'ENCAMISADO DE VIGA REFORZADA EN LOSA RETICULAR','unidad'=>'ML','porcentaje'=>'0','costo'=>'4594.63']);
            Actividad::create(['descripcion'=>'TENSOR','unidad'=>'M3','porcentaje'=>'0','costo'=>'1679.09']);
            Actividad::create(['descripcion'=>'COLUMNA C-2','unidad'=>'M3','porcentaje'=>'0','costo'=>'3325.08']);
            Actividad::create(['descripcion'=>'VIGA INTERMEDIA V-1','unidad'=>'M3','porcentaje'=>'0','costo'=>'1967.95']);
            Actividad::create(['descripcion'=>'SOLERA DE CORONA SC-4','unidad'=>'M3','porcentaje'=>'0','costo'=>'3325.05']);
            Actividad::create(['descripcion'=>'ZAPATA CORRIDA Z M-3','unidad'=>'M3','porcentaje'=>'0','costo'=>'1085.96']);
            Actividad::create(['descripcion'=>'ZAPATA AISLADA Z-2','unidad'=>'M3','porcentaje'=>'0','costo'=>'1299.91']);
            Actividad::create(['descripcion'=>'SOLERA DE FUNDACION SF-1','unidad'=>'M3','porcentaje'=>'0','costo'=>'1578.56']);
            Actividad::create(['descripcion'=>'NERVIOS N-2, N-3, N-4','unidad'=>'M3','porcentaje'=>'0','costo'=>'3642.89']);
            Actividad::create(['descripcion'=>'MENSULA EN COLUMNAS C-2','unidad'=>'M3','porcentaje'=>'0','costo'=>'3324.93']);
            Actividad::create(['descripcion'=>'CANAL DE CR','unidad'=>'M3','porcentaje'=>'0','costo'=>'3642.95']);
            Actividad::create(['descripcion'=>'LOSA EN VOLADIZO DE CR','unidad'=>'M3','porcentaje'=>'0','costo'=>'2182.18']);
            Actividad::create(['descripcion'=>'SOLERA DE CORONA SC-2','unidad'=>'M3','porcentaje'=>'0','costo'=>'2857.14']);
            Actividad::create(['descripcion'=>'ZAPATA CORRIDA Z M-1, Z M-2','unidad'=>'M3','porcentaje'=>'0','costo'=>'1732.22']);
            Actividad::create(['descripcion'=>'SOLERA DE CORONA SC-1 EN M-1, M-2','unidad'=>'M3','porcentaje'=>'0','costo'=>'3057.33']);
            Actividad::create(['descripcion'=>'SOLERA SF-3','unidad'=>'M3','porcentaje'=>'0','costo'=>'1500.13']);
            Actividad::create(['descripcion'=>'VIGA CANAL','unidad'=>'M3','porcentaje'=>'0','costo'=>'2857.16']);
            Actividad::create(['descripcion'=>'REPELLO Y AFINADO DE VIGA','unidad'=>'M2','porcentaje'=>'0','costo'=>'78.58']);
            Actividad::create(['descripcion'=>'REPELLO Y AFINADO DE LOSA','unidad'=>'M2','porcentaje'=>'0','costo'=>'44.3']);
            Actividad::create(['descripcion'=>'PISO DE CEMENTO 30X30','unidad'=>'M2','porcentaje'=>'0','costo'=>'160.78']);
            Actividad::create(['descripcion'=>'REPELLO DE COLUMNA','unidad'=>'ML','porcentaje'=>'0','costo'=>'44.3']);
            Actividad::create(['descripcion'=>'PANTALLA MURO','unidad'=>'M2','porcentaje'=>'0','costo'=>'234.42']);
            Actividad::create(['descripcion'=>'PARED DE BLOQUE DE 15','unidad'=>'M2','porcentaje'=>'0','costo'=>'192.97']);
            Actividad::create(['descripcion'=>'CONTRAFUERTE','unidad'=>'C/U','porcentaje'=>'0','costo'=>'464.34']);
            Actividad::create(['descripcion'=>'REPELLO Y AFINADO DE PARED','unidad'=>'M2','porcentaje'=>'0','costo'=>'44.31']);
            Actividad::create(['descripcion'=>'ENCHAPADO DE AZULEJO','unidad'=>'M2','porcentaje'=>'0','costo'=>'196.45']);
            Actividad::create(['descripcion'=>'VIGA METALICA VM-1','unidad'=>'ML','porcentaje'=>'0','costo'=>'178.64']);
            Actividad::create(['descripcion'=>'POLIN C P-1','unidad'=>'ML','porcentaje'=>'0','costo'=>'44.31']);
            Actividad::create(['descripcion'=>'POLIN C P-2','unidad'=>'ML','porcentaje'=>'0','costo'=>'39.4']);
            Actividad::create(['descripcion'=>'INODORO COMPLETO','unidad'=>'C/U','porcentaje'=>'0','costo'=>'1059.3']);
            Actividad::create(['descripcion'=>'LAVAMANOS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'481.5']);
            Actividad::create(['descripcion'=>'URINARIO','unidad'=>'C/U','porcentaje'=>'0','costo'=>'1712']);
            Actividad::create(['descripcion'=>'TUBERIA PVC 6" (AGUAS LLUVIAS)','unidad'=>'ML','porcentaje'=>'0','costo'=>'136.67']);
            Actividad::create(['descripcion'=>'TUBERIA PVC 12"','unidad'=>'ML','porcentaje'=>'0','costo'=>'436.21']);
            Actividad::create(['descripcion'=>'TUBO PVC 1/2" 315 PSI','unidad'=>'ML','porcentaje'=>'0','costo'=>'12.86']);
            Actividad::create(['descripcion'=>'TUBERIA PVC 3/4"','unidad'=>'ML','porcentaje'=>'0','costo'=>'14.32']);
            Actividad::create(['descripcion'=>'GRIFOS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'78.11']);
            Actividad::create(['descripcion'=>'TUBERIA PVC 4" 160 PSI','unidad'=>'ML','porcentaje'=>'0','costo'=>'67.86']);
            Actividad::create(['descripcion'=>'TUBERIA PVC 6" (AGUAS NEGRAS)','unidad'=>'ML','porcentaje'=>'0','costo'=>'197.86']);
            Actividad::create(['descripcion'=>'TUBERIA PVC 3"','unidad'=>'ML','porcentaje'=>'0','costo'=>'45']);
            Actividad::create(['descripcion'=>'CAJA DE AGUAS NEGRAS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'178.58']);
            Actividad::create(['descripcion'=>'PINTURA DE PARED','unidad'=>'M2','porcentaje'=>'0','costo'=>'12.86']);
            Actividad::create(['descripcion'=>'PINTADO DE LOSAS DE ENTREPISO','unidad'=>'M2','porcentaje'=>'0','costo'=>'20.05']);
            Actividad::create(['descripcion'=>'IMPERMEABILIZACION DE LOSA DE CUBIERTAS','unidad'=>'M2','porcentaje'=>'0','costo'=>'247.85']);
            Actividad::create(['descripcion'=>'LAMINA DURALUM','unidad'=>'M2','porcentaje'=>'0','costo'=>'74.9']);
            Actividad::create(['descripcion'=>'CANALES DE AGUAS LLUVIAS','unidad'=>'ML','porcentaje'=>'0','costo'=>'160.74']);
            Actividad::create(['descripcion'=>'CANALETA DE AGUAS LLUVIAS MEDIA CAÑA','unidad'=>'ML','porcentaje'=>'0','costo'=>'112.03']);
            Actividad::create(['descripcion'=>'MALLA CICLON CON POSTES DE HIERRO H=2MTS','unidad'=>'M2','porcentaje'=>'0','costo'=>'232.13']);
            Actividad::create(['descripcion'=>'ACERA','unidad'=>'M2','porcentaje'=>'0','costo'=>'125.08']);
            Actividad::create(['descripcion'=>'DEMOLICION DE PISO','unidad'=>'M2','porcentaje'=>'0','costo'=>'10.7']);
            Actividad::create(['descripcion'=>'DEMOLICION DE PAREDES','unidad'=>'M2','porcentaje'=>'0','costo'=>'17.86']);
            Actividad::create(['descripcion'=>'CINCELADO DE REPELLO','unidad'=>'ML','porcentaje'=>'0','costo'=>'10.7']);
            Actividad::create(['descripcion'=>'DESMONTAJE DE PUERTAS Y VENTANAS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'19.31']);
            Actividad::create(['descripcion'=>'DESALOJO','unidad'=>'M3','porcentaje'=>'0','costo'=>'28.57']);
            Actividad::create(['descripcion'=>'VENTANA DE CELOSIA DE VIDRIO Y ALUMINIO ANODIZADO NATURAL','unidad'=>'M2','porcentaje'=>'0','costo'=>'392.86']);
            Actividad::create(['descripcion'=>'PUERTA METALICA','unidad'=>'C/U','porcentaje'=>'0','costo'=>'1029.6']);
            Actividad::create(['descripcion'=>'ENGRAMADO','unidad'=>'M2','porcentaje'=>'0','costo'=>'25']);
            Actividad::create(['descripcion'=>'LAMPARAS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'1250.03']);
            Actividad::create(['descripcion'=>'TOMACORRIENTES','unidad'=>'C/U','porcentaje'=>'0','costo'=>'714.23']);
            Actividad::create(['descripcion'=>'CAJA TERMICA DE 4 DADOS','unidad'=>'C/U','porcentaje'=>'0','costo'=>'2143.75']);
            Actividad::create(['descripcion'=>'PUERTA DE MADERA FORRADA DE PLYWOOD CUBIERTA DE FORMICA (0.70X1.55)','unidad'=>'C/U','porcentaje'=>'0','costo'=>'1003.41']);
            Actividad::create(['descripcion'=>'PUERTA DE MADERA ACCESO A SERVICIO SANITARIO P-3','unidad'=>'C/U','porcentaje'=>'0','costo'=>'1649.46']);
            Actividad::create(['descripcion'=>'PUERTA METALICA TIPO CORTINA (AREA DE CARGA/DESCARGA)','unidad'=>'C/U','porcentaje'=>'0','costo'=>'4280']);
            Actividad::create(['descripcion'=>'BOTAGUAS DE LAMINA GALVANIZADA','unidad'=>'ML','porcentaje'=>'0','costo'=>'107.18']);
            Actividad::create(['descripcion'=>'RESANADO DE GRIETAS LD Y MD EN PAREDES','unidad'=>'ML','porcentaje'=>'0','costo'=>'36.17']);
            Actividad::create(['descripcion'=>'EMPEDRADO(COMPACTADO C/ MAT. EXISTENTE)','unidad'=>'M2','porcentaje'=>'0','costo'=>'102.81']);
            Actividad::create(['descripcion'=>'ADOQUINADO','unidad'=>'M2','porcentaje'=>'0','costo'=>'179.7']);
            Actividad::create(['descripcion'=>'SOLERA FUNDACION SF-1(40X20 4#3+ 1#2 A.C. 15 CMS)','unidad'=>'ML','porcentaje'=>'0','costo'=>'108.13']);
            Actividad::create(['descripcion'=>'SOLERA DE FUNDACION SF (20X20 4#3+1#2 A.C. 15 CMS 1:2:2 )','unidad'=>'ML','porcentaje'=>'0','costo'=>'56.23']);
            Actividad::create(['descripcion'=>'SOLERA INTERMEDIA SI (15X20 2#3+1#4 A.C 15 CMS 1:2:2 )','unidad'=>'ML','porcentaje'=>'0','costo'=>'42.14']);
            Actividad::create(['descripcion'=>'SOLERA INTERMEDIA DE BLOQUE  2#3+1#2 @ 10 CMS 1:2:2','unidad'=>'ML','porcentaje'=>'0','costo'=>'51.03']);
            Actividad::create(['descripcion'=>'SOLERA CORONA 15X20  2#5+1#3 @ 20 CMS 1:2:2','unidad'=>'M3','porcentaje'=>'0','costo'=>'3752.17']);
            Actividad::create(['descripcion'=>'SOLERA CORONA BLOCK 20X20X40 2#3+1#2 @ 10 CMS 1:2:2','unidad'=>'ML','porcentaje'=>'0','costo'=>'80.29']);
            Actividad::create(['descripcion'=>'ALACRAN "A" 10 X 15 2#3+1#2 @ 15 CMS 1:2:2','unidad'=>'ML','porcentaje'=>'0','costo'=>'43.2']);
            Actividad::create(['descripcion'=>'NERVIO 15 X 15 4#3+1#2 @ 15 CMS 1:2:2','unidad'=>'ML','porcentaje'=>'0','costo'=>'63.91']);
            Actividad::create(['descripcion'=>'NERVIO N1 15 X 15 4#3+1#2 @ 15 CMS 1:2:2','unidad'=>'M3','porcentaje'=>'0','costo'=>'2994.89']);
            Actividad::create(['descripcion'=>'DEMOLICION DE PARED BLOQUE DE CONCRETO TIPO SPLIT FLUTED DE 0.20 X 0.20 0.40','unidad'=>'M2','porcentaje'=>'0','costo'=>'57.26']);
            Actividad::create(['descripcion'=>'REMOCION INTERNA DE BLOQUE DE CONCRETO','unidad'=>'M2','porcentaje'=>'0','costo'=>'17.17']);
            Actividad::create(['descripcion'=>'DEMOLICION DE PARED DE BLOQUE TIPO SALTEX DE 0.20 X 0.20 X 0.40','unidad'=>'M2','porcentaje'=>'0','costo'=>'22.9']);
            Actividad::create(['descripcion'=>'PISO ENCEMENTADO TIPO ACERA S/ PIEDRA CUARTA.','unidad'=>'M2','porcentaje'=>'0','costo'=>'111.19']);
            Actividad::create(['descripcion'=>'ENCEMENTADO TIPO ACERA','unidad'=>'ML','porcentaje'=>'0','costo'=>'132.85']);

    }
}
